### ISSUE TITLE
[Feature] Add ability to view/upload reports to Campaigns

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1093]
**Is your feature request related to a problem? Please describe.**
Users need to have more visibility on how each campaign progresses in terms of spending the donated funds and achieving the campaign goal. To make this possible, we need to enable Organizers to upload Progress Reports/News with expenditures or activities.

**Describe the solution you'd like**
- [ ] The Organizer should be able to upload Campaign Reports through an "Upload Reports" visible only to him and the coordinator (when logged in). The button should open the "New Report Screen" where the upload can be done according to the Figma design here https://www.figma.com/file/MmvFKzUv6yE5U2wrOpWtwS/Podkrepi.bg?node-id=13440%3A38670&t=jzFzoWQsq3Myjs5x-0
- [ ] The Organizer/Coordinator should be able to edit already uploaded reports or add more files to existing report.
- [ ] The Campaign Reports should be visible on a separate tab on the Campaign Display page (see the screenshot below). The tab should display a grid with the list of Reports containing the main reports fields.
<img width="1358" alt="Screenshot 2022-11-08 at 13 52 33" src="https://user-images.githubusercontent.com/7055304/200827725-e57820ba-7c8f-45e8-902d-3be95a642cef.png">

**Additional context**
For similar functionality see Campaign File Upload and Campaign "Signal for Irregularity"

**Comment by batebobo** [comment]
Hi! I'd like to work on this task. Can you please assign me :pray: Also I've come up with the following initial questions (surely more to come) and I'll be grateful for your insights 🙇 
**Product**

* Do we want to keep track of versions of reports when editing? I imagine some form of change log that can vary in details i.e. “Ivan has updated this report yesterday” or “Ivan has updated the goals from X to Y”. In my mind this would give even more transparency to end users and make the “edit” operation not that “dark”.

* Would there be any manual validation from our side for uploaded files before showing them to end users? The case I have in mind is visible personal data in an uploaded document which would not be ideal for the uploader.

* Would we be able to delete files from reports? Only addition is mentioned in the task.

* This seems like a huge task. Can you think of ways to separate the functionality between several tasks - each with a sensible deliverable? I’m pondering the same now :)


**Tech**

* Since this is a rather big feature, I’d hide it behind a feature flag. Do you think this makes sense?

**Comment by kachar** [comment]
@batebobo @igoychev I'd strongly suggest that we add a page for the activity of the campaign in the Organizers page one by one, instead of uploading a document. This will reduce the management of spreadsheets and file formats, parsing, and so on.

- If we do that we can easily maintain the versions of the data.
- We can have a single way of adding and editing data in the platform.
- We can delete or soft delete the records that are already existing. This will be hard with a spreadsheet.
- We can validate the data on the backend for each record and provide a proper message.

Eventually, if we want to support mass upload we can add that as a separate issue and track the progress on its own.

We can split the task into BE/FE functionality. Feature flag might not be needed on the BE, but we can add the FE after the BE is ready.

**Comment by kachar** [comment]
@igoychev Looks like the design team has already prepared the activity form. Uploading a screenshot of the current version for brevity.

I'm not 100% sure that the form below matches the current task. Please help us get clarity on the visualization.

![Отчети](https://user-images.githubusercontent.com/893608/202684782-25e478bf-d3bc-481f-a7ee-3c2f34e45c0e.png)

**Comment by igoychev** [comment]
Hi Bobo and wow - great set of questions, so happy to see you thought of all aspects! 
The quick answer to all of them is of course YES!

I already assigned you for it and also marked it as EPIC to indicate it's huge indeed! We can break down in smaller tasks as you suggested, so let's start adding them.

Detailed answers to your questions:
- Do we want to keep track versions of reports when editing? 
   - YES with a field for description for user to indicate what was changed. 
- Manual validation from the Coordinator?
   - YES, we will need status of the uploaded file - suggesting draft, need-change, approved-private, approved-public, deleted. Only the Coordinator should be able to change the status.
- Do we allow to DELETE uploaded file? 
   - no, we just mark as deleted, to protect the history as you mentioned above
- Feature flag? 
   - YES, this should be simple and will be great to demonstrate how it works on dev.podkrepi.bg before we unlock it on prod

Just saw that Ilko @kachar also commented - the idea was to focus on enabling file uploads that can present what happened as narrative reports, and not so much to record expenses for which we have another Admin UI. 
The design itself, is somewhat richer than needed at this stage and still needs to be commented. 

TODO: We also need to engage a PM and Designer for detailed discussion, but in meantime I am sure we can start at least with the preliminary implementation components.

**Comment by batebobo** [comment]
Thanks both @kachar and @igoychev for your comments!

@kachar I don't have an opinion about adding expenses one by one instead of uploading files.
I agree to split the task into the suggested pieces. I'll create the corresponding tasks and link this issue.
We can indeed add FE after BE is ready, but even if we don't benefit from gradual roll-out, we'll still be able to enable/disable the feature without redeploying, which IMO is a great advantage.

@igoychev I agree that we need to discuss things also with a PM and a designer.

In general, I can start by implementing the BE with all info we have until now. As discussions progress, we'll decide whether to inlcude suggestions in this work item, or split them in separate ones for later.
