### ISSUE TITLE
[Epic] Financial expenses for organizators and admins

### ISSUE THREAD

**Issue by dimitur2204** [podkrepi-bg/frontend#1361]
## Is your feature request related to a problem? Please describe.
Currently organizators of campaigns have no way of adding and getting reports approved in any way. Everything is done manually. We need a way for organizers to create and admins then approve a certain expense, which then will be shown to the user on the campaign page.

## Describe the solution you'd like
We should have a:
* Organizer panel/page where they can create and see all the added expenses and in the future other functionality regarding the campaigns they organize.
* View for the admin to be able to approve the submitted by the organizer financial reports.
* A way to show to the regular users the currently approved expenses and how the campaign's resources have been used to achieve the goal

## Linked issues

- [x] https://github.com/podkrepi-bg/frontend/issues/1362
- [x] https://github.com/podkrepi-bg/frontend/issues/1363
- [x] https://github.com/podkrepi-bg/frontend/issues/1364
- [x] https://github.com/podkrepi-bg/api/issues/446

**Additional context**

**Comment by slavcho** [comment]
The listed tickets are closed now. So we can close this project.
There are enhancements and bugs in other tickets, but we can close this.
