### ISSUE TITLE
Enable subscription for payment of membership fee to Podkrepi.bg 

### ISSUE THREAD

**Issue by igoychev** [podkrepi-bg/frontend#1530]
### Which area(s) of Podkrepi.bg are affected? (leave empty if unsure)

Campaigns, Donations

#### Problem: 
Currently members of Podkrepi.bg are paying their membership fee via bank transfers and the process is managed manually. 

#### Goal: 
We want to make this more effective by applying the same process as managing a standard campaign with regular subscriptions. This will enable same visibility for the donations, the financial reports, news and notifications for the collection and management of the association funds.

#### Solution:
To make this possible, the best way is to allow donations on campaigns, which are not shown in the full list with all "active" campaigns. Such campaigns could be the campaigns in "approved" state and they still can be accessed with through a link to it.

#### Subtasks:
- [ ] enable donations on "approved" campaigns - need to check both frontend and backend for the condition if campaign.state is Active and extend it with OR Approved
- [ ] Create a campaign named "Подкрепи Подкрепи.бг"/"Support Podkrepi.bg" campaign
- [ ] Update podkrepi.bg/support_us page with new text that points to the new "Membership Campaign"

### Describe alternatives you've considered

Different way to implement "Membership donations" would require duplicating all the functionality of the existing campaigns, so this option was discarded.
