### ISSUE TITLE
[Feature] Cleanup contact module

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/frontend#306]
Cleaning up the contact module consists of several steps. Some of them are dependent on a previous step so keep that in mind. If you are not sure if you should pick something up, please ask.

- [ ] Split API types from database model #302 
- [ ] Add extra database tables #303 
- [ ] Abstract away the database implementation #304 
- [ ] Add integration tests #305
