### ISSUE TITLE
Create custom authentication

### ISSUE THREAD

**Issue by kachar** [podkrepi-bg/frontend#371]
The motivation here is to reduce the friction between different systems and provide smooth UX in a single application.

At the moment users are being sent to https://keycloak.podkrepi.bg/auth/realms/webapp-dev/protocol/openid-connect/auth in order to login to https://podkrepi.bg and this creates confusion.

Our API layer now supports authentication via `/login` and `/register` endpoints (Check [swagger](https://dev.podkrepi.bg/docs/))

What needs to be done:

- [ ] Replace Keycloak authentication screens (login & registration) with internal forms
  - [ ] Replace handler for login form
  - [ ] Replace handler for registration form
  - [ ] Handle cookie storage (either manually on the frontend or via XHR cookie by the backend)
- [ ] Recognize the session cookie and provide it to the `SSRKeycloakProvider`

**Comment by atanasster** [comment]
I’ll give it a go

**Comment by kachar** [comment]
Closing this issue as we'll stick with Keycloak authentication forms with a custom design.

All other solutions are quite complex and will require many many more hours to be polished and functional. In a perfect scenario, we would have enough people to complete it, but at this point in time, we don't have that luxury and need to stick to a more simple solution.

The current Keycloak solution is sufficient both on the backend and frontend as it provides ways to check for the permissions based on JWT token without custom implementations.

@atanasster Thanks for the energy and brainpower you've put into the PR.

![image](https://user-images.githubusercontent.com/893608/149507568-7822a210-8020-4727-99a4-5edc3b143c62.png)
